# Generated by Django 5.1.3 on 2024-12-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0004_alter_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(default='', upload_to='img/'),
        ),
    ]
