# Generated by Django 5.1.3 on 2024-12-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0007_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ts_segments_1080p',
            field=models.FileField(blank=True, null=True, upload_to='videos/1080p/segments/'),
        ),
        migrations.AddField(
            model_name='video',
            name='ts_segments_480p',
            field=models.FileField(blank=True, null=True, upload_to='videos/480p/segments/'),
        ),
        migrations.AddField(
            model_name='video',
            name='ts_segments_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos/720p/segments/'),
        ),
    ]
