# Generated by Django 5.1.3 on 2024-12-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoflix_app', '0008_video_ts_segments_1080p_video_ts_segments_480p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='ts_segments_1080p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='ts_segments_480p',
        ),
        migrations.RemoveField(
            model_name='video',
            name='ts_segments_720p',
        ),
    ]
